services:
  - type: web
    name: blobby-api
    runtime: docker
    dockerfilePath: apps/api/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AUTH_SESSION_SECRET
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: ADMIN_WALLETS
        sync: false
      - key: BSC_RPC_URL
        value: https://data-seed-prebsc-1-s1.binance.org:8545/
      - key: BSC_CHAIN_ID
        value: "97"
      - key: DAILY_DRAW_CONTRACT_ADDRESS
        sync: false
      - key: DAILY_DRAW_ADDRESS
        sync: false
      - key: JACKPOT_VAULT_CONTRACT_ADDRESS
        sync: false
      - key: PRICE_ADAPTER_CONTRACT_ADDRESS
        sync: false
      - key: BLOBBIE_TOKEN_ADDRESS
        sync: false
      - key: EXPLORER_BASE_URL
        value: https://testnet.bscscan.com

  - type: web
    name: blobby-realtime
    runtime: docker
    dockerfilePath: apps/realtime/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: worker
    name: blobby-worker
    runtime: docker
    dockerfilePath: apps/worker/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: BSC_RPC_URL
        value: https://data-seed-prebsc-1-s1.binance.org:8545/
      - key: BSC_CHAIN_ID
        value: "97"
      - key: DAILY_DRAW_CONTRACT_ADDRESS
        sync: false
      - key: DAILY_DRAW_ADDRESS
        sync: false
      - key: JACKPOT_VAULT_CONTRACT_ADDRESS
        sync: false
      - key: JACKPOT_VAULT_ADDRESS
        sync: false
      - key: PRICE_ADAPTER_CONTRACT_ADDRESS
        sync: false
      - key: WORKER_DRY_RUN
        value: "true"
      - key: WORKER_PRIVATE_KEY
        sync: false
      - key: CONTRACT_SYNC_START_BLOCK
        sync: false
      - key: CONTRACT_CONFIRMATION_DEPTH
        value: "12"
